"""Docs build step (DOCS-PLAN §1): dump openapi.json from the app factory and
render endpoint tables into docs-site/api/endpoints.md (MP-3 — the page grows
automatically as endpoints land; regenerated every CI run, --check fails on
drift so the published reference can never lag the code)."""

from __future__ import annotations

import sys
from pathlib import Path

REPO = Path(__file__).parents[1]
OUT_MD = REPO / "docs-site" / "api" / "endpoints.md"

HEADER = """\
# Endpoints

<!-- GENERATED by scripts/export_openapi.py from the live app factory — do not
edit by hand; CI regenerates and fails on drift (MP-3). -->

This page is generated from the application's OpenAPI schema on every CI run,
so it always matches the deployed code. Web pages (`/`, `/upload`, `/r/...`,
`/auth/...`, `/admin/...`) are session-driven and not part of the JSON API;
the JSON API lives under `/api/v1/` and returns the
[uniform error envelope](overview.md#errors) on failure.
"""


def build_app():
    from tokenops_cost_auditor.config import Settings
    from tokenops_cost_auditor.main import create_app

    return create_app(Settings(app_env="docs", _env_file=None))


def render(schema: dict) -> str:
    lines = [HEADER]
    for path in sorted(schema.get("paths", {})):
        operations = schema["paths"][path]
        for method in ("get", "post", "put", "delete", "patch"):
            if method not in operations:
                continue
            op = operations[method]
            lines.append(f"## `{method.upper()} {path}`")
            lines.append("")
            summary = op.get("summary") or ""
            description = (op.get("description") or "").strip()
            if summary:
                lines.append(summary + ("." if not summary.endswith(".") else ""))
            if description:
                lines.append("")
                lines.append(description.split("\n\n")[0])
            lines.append("")
            params = op.get("parameters", [])
            if params:
                lines.append("| Parameter | In | Required | Type |")
                lines.append("|---|---|---|---|")
                for p in params:
                    p_type = p.get("schema", {}).get("type", "string")
                    lines.append(
                        f"| `{p['name']}` | {p['in']} | {'yes' if p.get('required') else 'no'} "
                        f"| {p_type} |"
                    )
                lines.append("")
            responses = op.get("responses", {})
            if responses:
                codes = ", ".join(f"`{c}`" for c in sorted(responses))
                lines.append(f"Responses: {codes}")
                lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    check = "--check" in sys.argv
    app = build_app()
    rendered = render(app.openapi())
    if check:
        current = OUT_MD.read_text(encoding="utf-8") if OUT_MD.exists() else ""
        if current != rendered:
            print(
                "endpoints.md is stale — run `uv run python scripts/export_openapi.py` "
                "and commit (MP-3 drift gate)"
            )
            return 1
        print("endpoints.md up to date")
        return 0
    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT_MD}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
