"""WP-SELF docs build step (R-SELF-AUDIT b/c): render the self-audit ledger
into docs-site/engineering/self-audit-data.md.

Uses ONLY founder-verified rows (verified != ""). Below 3 verified rows the
page shows a MEASUREMENT-PENDING block instead of numbers — invented or
unverified figures never render. CI runs --check so the published page can
never drift from the committed ledger."""

from __future__ import annotations

import csv
import sys
from pathlib import Path

REPO = Path(__file__).parents[1]
LEDGER = REPO / "docs" / "internal" / "self-audit" / "ledger.csv"
OUT_MD = REPO / "docs-site" / "engineering" / "self-audit-data.md"
MIN_ROWS = 3  # R-SELF-AUDIT b: MEASUREMENT-PENDING until >=3 ledger rows

PENDING = """\
<!-- GENERATED by scripts/render_self_audit.py from docs/internal/self-audit/ledger.csv —
do not edit by hand; CI fails on drift. -->

!!! warning "MEASUREMENT-PENDING (WP-SELF)"
    The trendline appears here once at least three founder-verified
    self-audit ledger rows exist. Rows are verified the same way our golden
    files are: independently recomputed and signed off by name before
    anything built on them is published.
"""


def bar_chart_svg(rows: list[dict[str, str]]) -> str:
    width, height, pad = 640, 220, 36
    n = len(rows)
    bar_w = (width - 2 * pad) / max(n, 1) * 0.6
    max_pct = max(float(r["waste_pct"]) for r in rows) or 1.0
    parts = [
        f'<svg viewBox="0 0 {width} {height}" role="img" '
        f'aria-label="Waste percentage per self-audit run" '
        f'xmlns="http://www.w3.org/2000/svg">'
    ]
    for i, r in enumerate(rows):
        pct = float(r["waste_pct"])
        h = (height - 2 * pad) * pct / max_pct
        x = pad + (width - 2 * pad) * (i + 0.2) / n
        y = height - pad - h
        parts.append(
            f'<rect x="{x:.0f}" y="{y:.0f}" width="{bar_w:.0f}" height="{h:.0f}" fill="#c96442"/>'
        )
        parts.append(
            f'<text x="{x + bar_w / 2:.0f}" y="{height - pad + 16}" font-size="11" '
            f'text-anchor="middle">{r["date"][5:]}</text>'
        )
        parts.append(
            f'<text x="{x + bar_w / 2:.0f}" y="{y - 6:.0f}" font-size="12" '
            f'text-anchor="middle">{pct}%</text>'
        )
    parts.append("</svg>")
    return "".join(parts)


def render() -> str:
    rows: list[dict[str, str]] = []
    if LEDGER.exists():
        with LEDGER.open(encoding="utf-8") as fh:
            rows = [r for r in csv.DictReader(fh) if r.get("verified", "").strip()]
    if len(rows) < MIN_ROWS:
        return PENDING
    lines = [
        "<!-- GENERATED by scripts/render_self_audit.py from docs/internal/self-audit/ledger.csv —",
        "do not edit by hand; CI fails on drift. Verified rows only. -->",
        "",
        "| Date | Sessions | Calls | API-equiv spend | Est. monthly waste | Waste % |",
        "|---|---|---|---|---|---|",
    ]
    total_spend = 0.0
    for r in rows:
        total_spend += float(r["observed_api_equiv_spend_usd"])
        lines.append(
            f"| {r['date']} | {r['sessions']} | {int(r['calls']):,} "
            f"| ${float(r['observed_api_equiv_spend_usd']):,.2f} "
            f"| ${float(r['est_monthly_waste_usd']):,.2f} | {r['waste_pct']}% |"
        )
    lines += [
        "",
        f"Cumulative audited build cost (API-equivalent): **${total_spend:,.2f}** "
        f"across {len(rows)} verified runs.",
        "",
        bar_chart_svg(rows),
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    rendered = render()
    if "--check" in sys.argv:
        current = OUT_MD.read_text(encoding="utf-8") if OUT_MD.exists() else ""
        if current != rendered:
            print("self-audit-data.md stale — run `uv run python scripts/render_self_audit.py`")
            return 1
        print("self-audit-data.md up to date")
        return 0
    OUT_MD.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT_MD}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
